# Mean and Variance 

In [3]:
import numpy as np

def compute_mean(array):
    return np.mean(array)

def compute_variance(array, sample=True):
    if sample:
        return np.var(array, ddof=1)
    else:
        return np.var(array)

def main():
    sample_vector = np.array([float(input(f"Enter element {i+1}: ")) for i in range(int(input("Enter the dimension of the vector: ")))])

    print("Sample Vector:", sample_vector)
    mean = compute_mean(sample_vector)
    sample_variance = compute_variance(sample_vector)
    population_variance = compute_variance(sample_vector, sample=False)

    print("Mean:", mean)
    print("Sample Variance:", sample_variance)
    print("Population Variance:", population_variance)

if __name__ == "__main__":
    main()

Enter the dimension of the vector:  5
Enter element 1:  1
Enter element 2:  2
Enter element 3:  3
Enter element 4:  4
Enter element 5:  5


Sample Vector: [1. 2. 3. 4. 5.]
Mean: 3.0
Sample Variance: 2.5
Population Variance: 2.0


# Covariance between two vectors

In [4]:
### cov(X, Y) = Σ((Xi - X̄) * (Yi - Ȳ)) / n-1
import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.sum((vector1 - np.mean(vector1)) * (vector2 - np.mean(vector2))) / (len(vector1) - 1)
    return covariance

def main():
    M = int(input("Enter the dimension of vector 1: "))
    N = int(input("Enter the dimension of vector 2: "))

    vector1 = np.array(input(f"Enter {M} elements for vector 1 separated by spaces: ").split(), dtype=float)
    vector2 = np.array(input(f"Enter {N} elements for vector 2 separated by spaces: ").split(), dtype=float)

    covariance = compute_covariance(vector1, vector2)

    print("Covariance between Vector 1 and Vector 2:", covariance)

if __name__ == "__main__":
    main()

Enter the dimension of vector 1:  3
Enter the dimension of vector 2:  3
Enter 3 elements for vector 1 separated by spaces:  1 2 3
Enter 3 elements for vector 2 separated by spaces:  4 7 8


Covariance between Vector 1 and Vector 2: 2.0


# Correlation

In [18]:
import numpy as np

def compute_correlation(vector1, vector2):
    covariance = np.cov(vector1, vector2)[0][1]
    correlation = covariance / (np.std(vector1) * np.std(vector2))
    return correlation

def main():
    N = int(input("Enter the dimension of the vectors: "))

    vector1 = np.array(input(f"Enter {N} elements for vector 1 separated by spaces: ").split(), dtype=float)
    vector2 = np.array(input(f"Enter {N} elements for vector 2 separated by spaces: ").split(), dtype=float)

    if len(vector1) != N or len(vector2) != N:
        print(f"Error: Vectors must be of length {N}.")
        return

    correlation = compute_correlation(vector1, vector2)

    print("Correlation between Vector 1 and Vector 2:", correlation)

if __name__ == "__main__":
    main()

Enter the dimension of the vectors:  3
Enter 3 elements for vector 1 separated by spaces:  1 2 3
Enter 3 elements for vector 2 separated by spaces:  4 5 6


Correlation between Vector 1 and Vector 2: 1.5


# Write a program to compute the covariance matrix and correlation matrix.

In [5]:
def calculate_covariance_matrix(data):
    mean = np.mean(data, axis=0)
    centered_data = data - mean
    covariance_matrix = np.cov(centered_data.T, bias=False)
    return covariance_matrix

def calculate_correlation_matrix(data):
    covariance_matrix = calculate_covariance_matrix(data)
    std_dev = np.std(data, axis=0)
    correlation_matrix = np.divide(covariance_matrix, np.outer(std_dev, std_dev), where=(std_dev[:, None] * std_dev[None, :]) != 0)
    return correlation_matrix

rows = int(input("Enter the number of rows (samples): "))
cols = int(input("Enter the number of columns (features): "))

data = np.zeros((rows, cols))

print("Enter the data:")
for i in range(rows):
    data[i] = [float(val) for val in input(f"Enter values for sample {i+1}: ").split()]

covariance_matrix = calculate_covariance_matrix(data)
correlation_matrix = calculate_correlation_matrix(data)

print("Covariance Matrix:\n", covariance_matrix)
print("Correlation Matrix:\n", correlation_matrix)

Enter the number of rows (samples):  3
Enter the number of columns (features):  3


Enter the data:


Enter values for sample 1:  1 6 7
Enter values for sample 2:  9 6 4
Enter values for sample 3:  6 0 2


Covariance Matrix:
 [[16.33333333 -2.         -7.16666667]
 [-2.         12.          7.        ]
 [-7.16666667  7.          6.33333333]]
Correlation Matrix:
 [[ 1.5        -0.21428571 -1.05695106]
 [-0.21428571  1.5         1.2044326 ]
 [-1.05695106  1.2044326   1.5       ]]
